services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      - DJANGO_DB_HOST=localhost
      - DJANGO_DB_NAME=bd
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=senha
